services:
  postgres:
    image: postgres:17
    container_name: ChatBotDemo-DB-Container
    environment:
      POSTGRES_DB: ${DB_NAME:-ChatBotDemo-DB}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "${DB_PORT:-5434}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: